### PR TITLE
feat: impl and expose SetIfNotExists API to clients/sdk

### PR DESCRIPTION
**Pull request by pratik151192**
Added implementation for ```SetIfNotExists``` with tests. Commit also exposes the API to our SDK once we release it.

### CODE REVIEW

**Comment by pratik151192** [comment]
There's something weird that whenever I push a new commit to an existing PR, all the CI workflows don't run and only a single one runs. If you look at the two commits, it ran 6 CI workflows for the first one in which ```lint``` failed due to some unused variable. I fixed that and pushed another commit, and only one CI workflow ran as a part of it. I saw this behavior in another PR. I'm wondering if it re-runs once the tracking branch is merged into main.

**Comment by cprice404** [comment]
> There's something weird that whenever I push a new commit to an existing PR, all the CI workflows don't run and only a single one runs. If you look at the two commits, it ran 6 CI workflows for the first one in which `lint` failed due to some unused variable. I fixed that and pushed another commit, and only one CI workflow ran as a part of it. I saw this behavior in another PR. I'm wondering if it re-runs once the tracking branch is merged into main.

Yes, look at the top of the yaml files and you will see stuff like this:

https://github.com/momentohq/client-sdk-go/blob/2bfc6b57614e9dc68f3539c3efce8d181e355ed8/.github/workflows/on-pull-request.yml#L4

This is telling it to only run this CI job for PRs that are targeted at `main`. This will happen once your other PR is merged, or alternately you can file a PR to change that yaml so that the workflow will run against all PRs.

**Review by cprice404 — APPROVED** [review]
🙈 , lgtm when @pgautier404 approves

**Review by pgautier404 — APPROVED** [review]
🚢

**Pull request merged**
