### PR TITLE
chore: adds code scanning workflow

### PR DESCRIPTION
**Pull request by eaddingtonwhite**

### CODE REVIEW

**Comment by eaddingtonwhite** [comment]
Looks good.
Screenshot 2022-12-05 at 5 11 01 PM

**Comment by bruuuuuuuce** [comment]
could this potentially go in the shared workflow https://github.com/momentohq/client-sdk-go/blob/main/.github/workflows/build.yml#L23?

**Comment by eaddingtonwhite** [comment]
@bruuuuuuuce potentially... it can be bit different depending on repo is only thing (see java sdk for example). We can revisit though down line I wanted to get feel for this check first and break out to start.

**Review by bruuuuuuuce — APPROVED** [review]
:shipit:

**Pull request merged**
