### PR TITLE
feat: impl and expose SortedSetLength, SortedSetLengthByScore, DictionaryLength, and SetLength to client/sdk

### PR DESCRIPTION
**Pull request by pratik151192**
Implemented SortedSetLength, SortedSetLengthByScore, DictionaryLength, and SetLength APIs and made it visible from our SDK. Models are here in this umerged [PR](https://github.com/momentohq/client-sdk-go/pull/338) and changes have been done in this PR only for SortedSetLengthByScore after discussions around how we want to design minScore and maxScore inclusiveness. Both will be merged together.

### CODE REVIEW

**Comment by cprice404** [comment]
@pratik151192 what would you think about closing that other PR and just targeting this against `main` so we can see everything in one shot?

**Comment by pratik151192** [comment]
> Member

Done!

**Review by cprice404 — DISMISSED** [review]
this looks great to me!  would like for pete to spot check the request / response types but tests and stuff look very good from where i'm sitting :)

🚢

**Review by pgautier404 — APPROVED** [review]
LGTM!

**Pull request merged**
